name: Build MAUI Apps

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI Workloads
      run: |
        dotnet workload install maui maui-android maui-windows

    - name: Build Android APK
      run: |
        dotnet publish FreeFireOptimizer/FreeFireOptimizer.csproj -f net8.0-android -c Release

    - name: Build Windows EXE
      run: |
        dotnet publish FreeFireOptimizer/FreeFireOptimizer.csproj -f net8.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: FreeFireOptimizer-Android-APK
        path: |
          **/bin/Release/net8.0-android/*Signed.apk
          **/bin/Release/net8.0-android/*.apk

    - name: Upload Windows EXE
      uses: actions/upload-artifact@v4
      with:
        name: FreeFireOptimizer-Windows-EXE
        path: **/bin/Release/net8.0-windows10.0.19041.0/win10-x64/publish/
